#!/usr/bin/env cwl-runner
class: CommandLineTool
cwlVersion: v1.0
label: "bwa index process"
doc: |
  "bwa index create process from predicted protein conding sequences for executing BWA-MEM process
  modified from https://github.com/common-workflow-library/bio-cwl-tools/blob/release/bwa/BWA-Index.cwl
  original script: https://github.com/RyoMameda/workflow/blob/main/05_mapping.sh
  original command: bwa index -p index_${f}_bwa ${f}.fna"

requirements:
  WorkReuse:
    enableReuse: true
  ShellCommandRequirement: {}
  InlineJavascriptRequirement: {}

arguments:
  - shellQuote: false
    valueFrom: |
      mkdir -p index_$(inputs.input_fasta_file.basename.replace(/\.(gz|bz2|fa|fasta|fna|faa)$/, ''))_dir
      touch index_$(inputs.input_fasta_file.basename.replace(/\.(gz|bz2|fa|fasta|fna|faa)$/, ''))_dir/index_$(inputs.input_fasta_file.basename.replace(/\.(gz|bz2|fa|fasta|fna|faa)$/, '')) # create empty file
      bwa index -p index_$(inputs.input_fasta_file.basename.replace(/\.(gz|bz2|fa|fasta|fna|faa)$/, ''))_dir/index_$(inputs.input_fasta_file.basename.replace(/\.(gz|bz2|fa|fasta|fna|faa)$/, '')) $(inputs.input_fasta_file.path)

inputs:
  - id: input_fasta_file
    type: File
    label: "input dna fasta file"
    doc: "input predicted protein conding DNA sequences fasta file generated by prodigal process"
    default:
      class: File
      location: ../out/all_contigs_SRR27548858_dna.fasta

outputs:
  # - id: all-for-debugging
  #   type:
  #     type: array
  #     items: [File, Directory]
  #   outputBinding:
  #     glob: "*"

  - id: index_bwa_dir
    type: Directory
    label: "index bwa dir"
    doc: "index files will be contained in this directry"
    outputBinding:
      glob: index_$(inputs.input_fasta_file.basename.replace(/\.(gz|bz2|fa|fasta|fna|faa)$/, ''))_dir

  - id: index_bwa_files
    type: File
    label: "index bwa files"
    doc: "index files' name for BWA-MEM"
    outputBinding:
      glob: index_$(inputs.input_fasta_file.basename.replace(/\.(gz|bz2|fa|fasta|fna|faa)$/, ''))_dir/index_$(inputs.input_fasta_file.basename.replace(/\.(gz|bz2|fa|fasta|fna|faa)$/, ''))
    secondaryFiles:
      - .amb
      - .ann
      - .bwt
      - .pac
      - .sa
    

hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/bwa:0.7.17--he4a0461_11

$namespaces:
  s: https://schema.org/
  edam: https://edamontology.org/
