#!/usr/bin/env cwl-runner
class: CommandLineTool
cwlVersion: v1.2
label: "bwa index process"
doc: |
  "bwa index create process for executing bwa mem process
  original script: https://github.com/RyoMameda/workflow/blob/main/05_mapping.sh
  original command: bwa index -p index_${f}_bwa ${f}.fna"

requirements:
  WorkReuse:
    enableReuse: true

baseCommand: [bwa, index]

arguments:
  - -p
  - $(inputs.index_bwa_name)
  - $(inputs.input_fasta_file.path)

inputs:
  - id: index_bwa_name
    type: string
    label: "index bwa name"
    doc: "index bwa name"
    default: "index_bwa"

  - id: input_fasta_file
    type: File
    label: "input dna fasta file"
    doc: "input dna fasta file generated by prodigal process"
    default:
      class: File
      location: ../out/all_contigs_SRR27548858_dna.fasta

outputs:
  - id: all-for-debugging
    type:
      type: array
      items: [File, Directory]
    outputBinding:
      glob: "*"

hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/bwa:0.7.17--he4a0461_11

$namespaces:
  s: https://schema.org/
  edam: https://edamontology.org/